version: '3.8'

services:

  postgres:
    image: "postgres:13.0"
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: test

  redis:
    image: "redis:6.0.9"
    ports:
      - 6378:6379